// action - customization reducer
export const SESSION_LOGIN = '@SESSION/LOGIN';
export const SESSION_LOGOUT = '@SESSION/LOGOUT';

export const USERS_GETALL = '@USERS/GETALL';
export const USERS_GETONE = '@USERS/GETONE';
export const USERS_CREATE = '@USERS/CREATE';
export const USERS_UPDATE = '@USERS/UPDATE';
export const USERS_DELETE = '@USERS/DELETE';

export const PROPERTIES_GETALL = '@PROPERTIES/GETALL';
export const PROPERTIES_GETONE = '@PROPERTIES/GETONE';
export const PROPERTIES_CREATE = '@PROPERTIES/CREATE';
export const PROPERTIES_UPDATE = '@PROPERTIES/UPDATE';
export const PROPERTIES_DELETE = '@PROPERTIES/DELETE';
