version: '3.3'
services:
  # mysql:
  #   image: mysql
  #   # restart: always
  #   environment:
  #     MYSQL_DATABASE: 'ECOMECHANICAL'
  #     MYSQL_USER: 'ECOMEC_ADMIN'
  #     MYSQL_PASSWORD: '4356ybtwea4b6w34h7b56'
  #     MYSQL_ROOT_PASSWORD: 'qwfeasdfgawfwef'
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - mySQL:/var/lib/mysql

  movies:
    image: mysql
    # restart: always
    environment:
      MYSQL_DATABASE: 'movies'
      MYSQL_USER: 'Peliculas'
      MYSQL_PASSWORD: 'jskadhf;oiaseufpoaiwsf@'
      MYSQL_ROOT_PASSWORD: 'qwfeasdfgawfwef'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mySQLMovies:/var/lib/mysql

  # mssql:
  #   image: mcr.microsoft.com/mssql/server
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "superSecretPasswordPrograWeb123!@"
  #     ACCEPT_EULA: "Y"
  #   volumes:
  #     - msSQL:/var/opt/mssql

volumes:
  mySQL:
  mySQLMovies:
  # msSQL: